/**
 * Farm Defense Themes — mirrors labyrinth's theme structure.
 * Each theme has a label, scene narrative, and color palette.
 * Frontend applies via CSS custom properties on document.documentElement.
 */

const DEFAULT_THEMES = {
  obsidian: {
    label: "Obsidian",
    description: "Dark fortress with neon crystal spires.",
    scene: {
      title: "Obsidian Fortress",
      path: "lava channel",
      towers: "crystal spires",
      enemies: "shadow creatures",
      buildable: "obsidian shelf",
      icon: "fa-chess-rook",
    },
    palette: {
      accent: "#63f5ff",
      accentSoft: "rgba(99, 245, 255, 0.16)",
      background: "#0a0d12",
      panel: "rgba(12, 15, 22, 0.78)",
      border: "rgba(112, 141, 255, 0.12)",
      path: "#8b6914",
      buildable: "#1a3a1a",
      blocked: "#1a1a2e",
      tower: "#63f5ff",
      enemy: "#ff4757",
      projectile: "#ffd700",
      spawn: "#ff6b6b",
      exit: "#7bff9d",
    },
  },
  fields: {
    label: "Fields",
    description: "Farm fortress — scarecrows defend against pest swarms.",
    scene: {
      title: "Farm Fortress",
      path: "dirt road",
      towers: "scarecrows",
      enemies: "pest swarm",
      buildable: "fertile plot",
      icon: "fa-wheat-awn",
    },
    palette: {
      accent: "#7bff9d",
      accentSoft: "rgba(123, 255, 157, 0.16)",
      background: "#0d120a",
      panel: "rgba(20, 26, 14, 0.86)",
      border: "rgba(123, 255, 157, 0.18)",
      path: "#6b4e1a",
      buildable: "#2a4a1a",
      blocked: "#1a2a1a",
      tower: "#7bff9d",
      enemy: "#ff6b6b",
      projectile: "#ffd700",
      spawn: "#ff4757",
      exit: "#99e86f",
    },
  },
  ember: {
    label: "Ember",
    description: "Warm lantern-lit fortress against fire imps.",
    scene: {
      title: "Ember Keep",
      path: "molten trail",
      towers: "lantern posts",
      enemies: "fire imps",
      buildable: "scorched earth",
      icon: "fa-fire",
    },
    palette: {
      accent: "#ffb15c",
      accentSoft: "rgba(255, 177, 92, 0.16)",
      background: "#11110d",
      panel: "rgba(22, 20, 14, 0.86)",
      border: "rgba(255, 177, 92, 0.18)",
      path: "#5c3d1a",
      buildable: "#2d3a1a",
      blocked: "#1a1a14",
      tower: "#ffb15c",
      enemy: "#ff4757",
      projectile: "#ffd700",
      spawn: "#ff6b6b",
      exit: "#7bff9d",
    },
  },
  mint: {
    label: "Mint",
    description: "Cool glass towers in an icy garden.",
    scene: {
      title: "Mint Garden",
      path: "frost walk",
      towers: "glass pillars",
      enemies: "ice shards",
      buildable: "frozen soil",
      icon: "fa-snowflake",
    },
    palette: {
      accent: "#5ff5c8",
      accentSoft: "rgba(95, 245, 200, 0.16)",
      background: "#0a120f",
      panel: "rgba(14, 22, 18, 0.86)",
      border: "rgba(95, 245, 200, 0.18)",
      path: "#3d5c4a",
      buildable: "#1a3a2a",
      blocked: "#0f1a16",
      tower: "#5ff5c8",
      enemy: "#ff6b6b",
      projectile: "#ffd700",
      spawn: "#ff4757",
      exit: "#7bff9d",
    },
  },
  graphite: {
    label: "Graphite",
    description: "Monochrome minimalist defence.",
    scene: {
      title: "Graphite Bunker",
      path: "concrete lane",
      towers: "steel turrets",
      enemies: "grey drones",
      buildable: "metal deck",
      icon: "fa-shield",
    },
    palette: {
      accent: "#b0b8c8",
      accentSoft: "rgba(176, 184, 200, 0.16)",
      background: "#0e0e10",
      panel: "rgba(18, 18, 22, 0.86)",
      border: "rgba(176, 184, 200, 0.12)",
      path: "#3a3a3a",
      buildable: "#222222",
      blocked: "#141414",
      tower: "#b0b8c8",
      enemy: "#ff4757",
      projectile: "#ffd700",
      spawn: "#ff6b6b",
      exit: "#7bff9d",
    },
  },
};

module.exports = { DEFAULT_THEMES };
