/**
 * Demo catalog — inventory self-seeds these on first boot so search works out of
 * the box. Owned by a synthetic seed host ("seed-host") so real users' listings
 * are separate. Deterministic ids keep tests and demos stable.
 *
 * `district` holds a Polish city; the UI groups cities under their voivodeship.
 */
module.exports = [
  {
    id: "prop-tatra-cottage",
    hostId: "seed-host",
    name: "Tatra Highland Cottage",
    district: "Zakopane",
    type: "cottage",
    capacity: 4,
    basePrice: 120,
    policy: "moderate",
    amenities: ["kitchen", "fireplace", "parking"],
    photoRef: "tatra-cottage.jpg",
    active: true,
  },
  {
    id: "prop-baltic-room",
    hostId: "seed-host",
    name: "Baltic Seaside Room",
    district: "Sopot",
    type: "room",
    capacity: 2,
    basePrice: 90,
    policy: "flexible",
    amenities: ["breakfast", "wifi"],
    photoRef: "baltic-room.jpg",
    active: true,
  },
  {
    id: "prop-masuria-camp",
    hostId: "seed-host",
    name: "Masurian Lakeside Camping",
    district: "Giżycko",
    type: "camping",
    capacity: 6,
    basePrice: 35,
    policy: "strict",
    amenities: ["firepit", "water", "kayaks"],
    photoRef: "masuria-camp.jpg",
    active: true,
  },
  {
    id: "prop-wroclaw-loft",
    hostId: "seed-host",
    name: "Restored Barn Loft",
    district: "Wrocław",
    type: "room",
    capacity: 3,
    basePrice: 95,
    policy: "moderate",
    amenities: ["wifi", "parking", "animals"],
    photoRef: "wroclaw-loft.jpg",
    active: true,
  },
  {
    id: "prop-krakow-cottage",
    hostId: "seed-host",
    name: "Kazimierz Garden Cottage",
    district: "Kraków",
    type: "cottage",
    capacity: 5,
    basePrice: 140,
    policy: "moderate",
    amenities: ["kitchen", "garden", "wifi", "parking"],
    photoRef: "krakow-cottage.jpg",
    active: true,
  },
  {
    id: "prop-bieszczady-camp",
    hostId: "seed-host",
    name: "Bieszczady Wildlife Camp",
    district: "Ustrzyki Dolne",
    type: "camping",
    capacity: 8,
    basePrice: 40,
    policy: "flexible",
    amenities: ["firepit", "water", "animals"],
    photoRef: "bieszczady-camp.jpg",
    active: true,
  },
];
