import { describe, it, expect } from "vitest";

// The holidays page actually rendering (Phase 7 exit: "no console errors").
//
// That criterion is about a browser, and this repo has no browser driver and a rule
// against adding one (§10.2: no new dependency, no build step). So this is the
// closest automatable equivalent, and it is a fair one: the controller is driven
// through a DOM stub against a **response captured from the live server** — real
// balances, a real calendar with two people off, a real approval queue, and a real
// `LeaveBookedWithWarning` in its history.
//
// What that catches is the class of bug the criterion is really about: a renderer
// that throws on a shape the server actually produces. `renderBalances` meeting a
// member with `leave: null`, a `byType` bucket that is absent, a name containing a
// quote — every one of those is a blank page and a console stack in a browser, and a
// thrown error here.
//
// What it does NOT catch is layout and CSS. Those are eyeballed.
//
// The fixture is regenerated by hitting the running app; it is checked in so the test
// does not need a server.
const BOARD = require("../fixtures/crew-leave-board.json");

const { loadLeavePage, fire } = require("../helpers/crew-leave-harness");

let elements;
let CrewLeave;

/** Drive the page once and expose what the assertions need. */
async function loadPage(response) {
  const run = await loadLeavePage(response);
  elements = run.elements;
  CrewLeave = run.page;
  return run;
}

describe("the holidays page renders a real server response", () => {
  it("loads without throwing, and asks for the whole board in ONE call", async () => {
    const stub = await loadPage({ data: BOARD });

    const boardCalls = stub.calls.filter((call) => call.operation === stub.CrewApi.OPERATIONS.LEAVE_BOARD);
    expect(boardCalls).toHaveLength(1);
    // And nothing else: the calendar, the queue and the balances all came from it.
    expect(stub.calls).toHaveLength(1);
    expect(boardCalls[0].variables).toMatchObject({ from: expect.any(String), to: expect.any(String), asOf: expect.any(String) });
  });

  it("renders the policy panel from the real policy", async () => {
    await loadPage({ data: BOARD });
    const html = elements.get("leavePolicyPanel").innerHTML;
    expect(html).toContain("26 days at full time");
    expect(html).toContain("monthly");
    expect(html).not.toMatch(/No leave policy is configured/);
  });

  it("renders the approval queue with a decision button carrying the row's version", async () => {
    await loadPage({ data: BOARD });
    const html = elements.get("leaveApprovals").innerHTML;
    expect(html).toContain("data-leave-approve");
    expect(html).toContain("data-leave-reject");
    // The version is what makes two people working the queue safe.
    expect(html).toMatch(/data-leave-version="\d+"/);
    // And it names the person, not just the staff id.
    expect(html).toContain("Halina");
  });

  it("renders the calendar as a month GRID, not a row per day", async () => {
    await loadPage({ data: BOARD });
    const html = elements.get("leaveCalendar").innerHTML;

    // The point of the redesign: 31 days of August in five or six week rows, not 31.
    // Header row plus weeks — a day-per-row table would be 32.
    const rows = (html.match(/<tr/g) || []).length;
    expect(rows).toBeLessThanOrEqual(7);
    expect(rows).toBeGreaterThanOrEqual(6);

    // Seven columns, Monday first.
    expect(html).toMatch(/<th scope="col"><abbr title="Mon">M<\/abbr><\/th>/);
    expect((html.match(/<th scope="col"/g) || []).length).toBe(7);

    // Every day is a button carrying its own date, so a click knows what it hit.
    expect(html).toContain('data-leave-day="2026-08-24"');
    expect((html.match(/data-leave-day="/g) || []).length).toBe(BOARD.leaveCalendar.length);
  });

  it("shows initials in a cell and keeps the names for the day panel", async () => {
    // A cell is too small for a name. The initials carry the "who", the title carries
    // the detail, and the day panel carries it in full.
    await loadPage({ data: BOARD });
    const html = elements.get("leaveCalendar").innerHTML;

    expect(html).toContain(">HK<"); // Halina Kowalska
    expect(html).toContain(">MN<"); // Marek Nowak
    expect(html).toMatch(/title="Halina Kowalska — Annual/);
    // A pending request reads as provisional, as it does on the request tables.
    expect(html).toContain("crew-cal__chip--requested");
  });

  it("labels each day for a screen reader, because the chips are only initials", async () => {
    await loadPage({ data: BOARD });
    const html = elements.get("leaveCalendar").innerHTML;
    expect(html).toMatch(/aria-label="2026-08-24, 2 off"/);
    expect(html).toMatch(/aria-label="2026-08-0\d, nobody off"/);
  });

  it("collapses months with nothing in them and opens the ones with somebody off", async () => {
    // A year-long range would otherwise open twelve grids, which is the problem the
    // day-per-row table had in a different shape.
    const twoMonths = JSON.parse(JSON.stringify(BOARD));
    twoMonths.leaveCalendar = [
      ...BOARD.leaveCalendar,
      { date: "2026-09-01", weekend: false, publicHoliday: false, blackoutReason: null, absences: [] },
      { date: "2026-09-02", weekend: false, publicHoliday: false, blackoutReason: null, absences: [] },
    ];
    await loadPage({ data: twoMonths });
    const html = elements.get("leaveCalendar").innerHTML;

    expect(html).toContain("August 2026");
    expect(html).toContain("September 2026");

    // Split on the opening tags so each month is inspected on its own — slicing
    // BACKWARDS from a month name breaks for the first one, whose index is near zero.
    const months = html.split("<details").slice(1);
    const august = months.find((chunk) => chunk.includes("August 2026"));
    const september = months.find((chunk) => chunk.includes("September 2026"));

    // August has absences and opens; September has none and stays shut.
    expect(august.startsWith(' class="crew-month" open>')).toBe(true);
    expect(september.startsWith(' class="crew-month">')).toBe(true);
  });

  it("expands a day into the detail panel when it is clicked", async () => {
    await loadPage({ data: BOARD });
    // The grid is delegated, so clicking works on a re-rendered calendar too.
    const button = { getAttribute: (name) => (name === "data-leave-day" ? "2026-08-24" : null), closest: null };
    await fire(elements.get("leaveCalendar"), "click", { target: { closest: () => button } });

    const detail = elements.get("leaveDayDetail");
    expect(detail.hidden).toBe(false);
    expect(detail.innerHTML).toContain("2026-08-24");
    // Names in full here, with a link to each member.
    expect(detail.innerHTML).toContain("Halina");
    expect(detail.innerHTML).toContain("/crew-member.html?staffId=");
  });

  it("says so for a day nobody is off, rather than showing an empty panel", async () => {
    await loadPage({ data: BOARD });
    const quiet = BOARD.leaveCalendar.find((day) => (day.absences || []).length === 0).date;
    const button = { getAttribute: (name) => (name === "data-leave-day" ? quiet : null) };
    await fire(elements.get("leaveCalendar"), "click", { target: { closest: () => button } });

    expect(elements.get("leaveDayDetail").innerHTML).toMatch(/Nobody is off/);
  });

  it("closes the day panel from its own button", async () => {
    await loadPage({ data: BOARD });
    const open = { getAttribute: (name) => (name === "data-leave-day" ? "2026-08-24" : null) };
    await fire(elements.get("leaveCalendar"), "click", { target: { closest: () => open } });
    expect(elements.get("leaveDayDetail").hidden).toBe(false);

    const close = { getAttribute: (name) => (name === "data-leave-day-close" ? "1" : null) };
    await fire(elements.get("leaveCalendar"), "click", { target: { closest: () => close } });
    expect(elements.get("leaveDayDetail").hidden).toBe(true);
  });

  it("renders every balance row, including members with no entitlement", async () => {
    await loadPage({ data: BOARD });
    const html = elements.get("leaveBalances").innerHTML;
    // Halina is full-time on 26 days; Marek is half-time on 13.
    expect(html).toContain("Halina");
    expect(html).toContain("Marek");
    // A member with no profile is explained rather than shown as zeroes.
    expect(html).toMatch(/no employment profile|<\/table>/);
    // One row per member, plus the <thead> row. Nobody is dropped for lacking a
    // balance — the roster on this page has to match the roster everywhere else.
    expect((html.match(/<tr/g) || []).length).toBe(BOARD.crew.nodes.length + 1);
  });

  it("summarises the range, the queue and the roster", async () => {
    await loadPage({ data: BOARD });
    const summary = elements.get("leaveSummary").textContent;
    expect(summary).toContain("awaiting a decision");
    expect(summary).toContain("on the roster");
  });

  it("populates the request form's member list from the same crew", async () => {
    await loadPage({ data: BOARD });
    const options = elements.get("leaveReqMember").innerHTML;
    expect(options).toContain("Halina");
    expect(options).toContain("<option");
  });

  it("escapes what it renders", async () => {
    // A name is user-supplied. Interpolating it raw is an XSS, and the module renders
    // everything through `innerHTML`.
    const nasty = JSON.parse(JSON.stringify(BOARD));
    nasty.crew.nodes[0].name = '<img src=x onerror="alert(1)">';
    await loadPage({ data: nasty });

    const html = elements.get("leaveBalances").innerHTML;
    expect(html).not.toContain("<img src=x");
    expect(html).toContain("&lt;img");
  });
});

describe("the holidays page degrades rather than emptying", () => {
  it("explains a missing policy instead of showing zeroes", async () => {
    // The §7.3 shape: `leave` null-propagates and one error arrives alongside a
    // rendered page. "Not configured" and "no days left" are different statements.
    const noPolicy = JSON.parse(JSON.stringify(BOARD));
    noPolicy.leavePolicy = null;
    noPolicy.crew.nodes = noPolicy.crew.nodes.map((node) => ({ ...node, leave: null }));

    await loadPage({ data: noPolicy, errors: null });

    expect(elements.get("leavePolicyPanel").innerHTML).toMatch(/No leave policy is configured/);
    // The calendar and the roster still render — the page is not blank.
    expect(elements.get("leaveCalendar").innerHTML).toContain("2026-08");
    expect(elements.get("leaveBalances").innerHTML).toMatch(/no employment profile|no balance available/);
  });

  it("says so when the leave pillar is not assembled, rather than showing an empty calendar", async () => {
    const noPillar = { crewInfo: { pillars: ["profiles", "work"] } };
    await loadPage({ data: noPillar });

    expect(elements.get("leavePolicyPanel").innerHTML).toMatch(/not assembled in this build/);
    expect(elements.get("leaveCalendar").innerHTML).toBe("");
  });

  it("reports a failed load rather than rendering a half page", async () => {
    await loadPage({ data: null, errors: [{ message: "boom", extensions: { code: "INTERNAL_ERROR" } }] });
    // The status line says something, and no panel was left with half a table in it.
    expect(elements.get("leaveStatus").textContent).toBeTruthy();
    expect(elements.get("leaveCalendar").innerHTML).toBe("");
    expect(elements.get("leaveBalances").innerHTML).toBe("");
  });

  it("survives a member whose balance is missing a byType or a nextBooked", async () => {
    // Shapes the server can legally produce, and the ones a renderer trips over.
    const sparse = JSON.parse(JSON.stringify(BOARD));
    sparse.crew.nodes = sparse.crew.nodes.map((node) => ({ ...node, leave: node.leave ? { ...node.leave, nextBooked: null } : null }));
    await expect(loadPage({ data: sparse })).resolves.toBeTruthy();
    expect(elements.get("leaveBalances").innerHTML).toContain("<table");
  });

  it("renders an empty calendar range and an empty queue without special-casing", async () => {
    const empty = JSON.parse(JSON.stringify(BOARD));
    empty.leaveCalendar = [];
    empty.pendingLeaveApprovals = [];
    empty.crew.nodes = [];
    await loadPage({ data: empty });

    expect(elements.get("leaveApprovals").innerHTML).toMatch(/Nothing is waiting/);
    expect(elements.get("leaveCalendar").innerHTML).toMatch(/No days in that range/);
    expect(elements.get("leaveBalances").innerHTML).toMatch(/Nobody on the roster/);
  });
});
