const policies = {
  "transaction.created": {
    id: "policy.transaction.default",
    eventType: "transaction.created",
    priority: "high",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 60 },
    rateLimit: { max: 10, windowSeconds: 300 },
    processingDelayMs: 2000,
    template: (event) => ({
      title: "Transaction Created",
      message: `Transaction #${event.payload?.transactionId || "n/a"} created with amount ${event.payload?.amount ?? "?"}.`,
    }),
  },
  "user.account.created": {
    id: "policy.user.account.created",
    eventType: "user.account.created",
    priority: "high",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 86400 },
    rateLimit: { max: 100, windowSeconds: 86400 },
    processingDelayMs: 3000,
    template: (event) => ({
      title: "User Account Created",
      message: `User account ${event.payload?.email || event.payload?.userId || "new user"} has been created.`,
    }),
  },
  "field.created": {
    id: "policy.field.created",
    eventType: "field.created",
    priority: "normal",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 0 },
    rateLimit: { max: 20, windowSeconds: 86400 },
    processingDelayMs: 1500,
    template: (event) => ({
      title: "Field Created",
      message: `Field ${event.payload?.name || `#${event.payload?.fieldId || "n/a"}`} has been created.`,
    }),
  },
  "staff.created": {
    id: "policy.staff.created",
    eventType: "staff.created",
    priority: "normal",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 0 },
    rateLimit: { max: 10, windowSeconds: 86400 },
    processingDelayMs: 1800,
    template: (event) => ({
      title: "Staff Created",
      message: `New staff member ${event.payload?.name || event.payload?.staffId || "(no name)"} has been added.`,
    }),
  },
  "animal.created": {
    id: "policy.animal.created",
    eventType: "animal.created",
    priority: "normal",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 0 },
    rateLimit: { max: 50, windowSeconds: 86400 },
    processingDelayMs: 1500,
    template: (event) => ({
      title: "Animal Created",
      message: `New animal of type ${event.payload?.type || "n/a"} added (quantity: ${event.payload?.amount ?? "?"}).`,
    }),
  },
  "animal.assigned": {
    id: "policy.animal.assigned",
    eventType: "animal.assigned",
    priority: "normal",
    channels: ["in-app"],
    dedupe: { seconds: 0 },
    rateLimit: { max: 10, windowSeconds: 86400 },
    processingDelayMs: 2500,
    template: (event) => ({
      title: "Animal Assigned",
      message: `Animal #${event.payload?.animalId || "n/a"} assigned to field #${event.payload?.fieldId || "n/a"}.`,
    }),
  },
  "marketplace.offer.created": {
    id: "policy.marketplace.offer.created",
    eventType: "marketplace.offer.created",
    priority: "normal",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 0 },
    rateLimit: { max: 30, windowSeconds: 86400 },
    processingDelayMs: 1500,
    template: (event) => ({
      title: "Marketplace Offer Created",
      message: `Offer #${event.payload?.offerId || "n/a"} (${event.payload?.itemType || "item"}) listed for ${event.payload?.price ?? "?"} ROL.`,
    }),
  },
  "marketplace.purchase.completed": {
    id: "policy.marketplace.purchase.completed",
    eventType: "marketplace.purchase.completed",
    priority: "high",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 30 },
    rateLimit: { max: 30, windowSeconds: 86400 },
    processingDelayMs: 2000,
    template: (event) => ({
      title: "Marketplace Purchase Completed",
      message: `Purchased ${event.payload?.itemType || "item"} from offer #${event.payload?.offerId || "n/a"} for ${event.payload?.price ?? "?"} ROL.`,
    }),
  },
  "transfer.completed": {
    id: "policy.transfer.completed",
    eventType: "transfer.completed",
    priority: "high",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 10 },
    rateLimit: { max: 50, windowSeconds: 86400 },
    processingDelayMs: 2000,
    template: (event) => ({
      title: "Transfer Completed",
      message: `Transferred ${event.payload?.amount ?? "?"} ROL to user #${event.payload?.toUserId || "n/a"}.`,
    }),
  },
  "user.login.failed": {
    id: "policy.user.login.failed",
    eventType: "user.login.failed",
    priority: "high",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 30 },
    rateLimit: { max: 100, windowSeconds: 3600 },
    processingDelayMs: 1500,
    template: (event) => ({
      title: "User Login Failed",
      message: `Detected failed login attempt (${event.payload?.reason || "unknown_reason"}).`,
    }),
  },
  "user.login.invalid_credentials": {
    id: "policy.user.login.invalid_credentials",
    eventType: "user.login.invalid_credentials",
    priority: "high",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 30 },
    rateLimit: { max: 100, windowSeconds: 3600 },
    processingDelayMs: 1500,
    template: (event) => ({
      title: "Invalid Login Credentials",
      message: `Invalid credentials used for login (${event.payload?.attemptedEmail || "unknown_user"}).`,
    }),
  },
  "user.registration.failed.user_exists": {
    id: "policy.user.registration.failed.user_exists",
    eventType: "user.registration.failed.user_exists",
    priority: "normal",
    channels: ["in-app", "webhook"],
    dedupe: { seconds: 60 },
    rateLimit: { max: 100, windowSeconds: 3600 },
    processingDelayMs: 1500,
    template: (event) => ({
      title: "Registration Failed: User Exists",
      message: `Registration was rejected because account ${event.payload?.attemptedEmail || "unknown_user"} already exists.`,
    }),
  },
};

module.exports = policies;
